# Generated by Django 2.2.17 on 2020-11-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20201117_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('thumbnail', 'thumbnail')], default='', max_length=256),
        ),
    ]
