# Generated by Django 2.2.17 on 2020-11-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_picture_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='owner',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
